BEGIN TRY

BEGIN TRAN;

-- CreateTable
CREATE TABLE [dbo].[CartItem] (
    [id] INT NOT NULL IDENTITY(1,1),
    [sessionId] NVARCHAR(1000) NOT NULL,
    [productId] INT NOT NULL,
    [quantity] INT NOT NULL,
    [addedAt] DATETIME2 NOT NULL CONSTRAINT [CartItem_addedAt_df] DEFAULT CURRENT_TIMESTAMP,
    CONSTRAINT [CartItem_pkey] PRIMARY KEY CLUSTERED ([id])
);

-- AddForeignKey
ALTER TABLE [dbo].[CartItem] ADD CONSTRAINT [CartItem_productId_fkey] FOREIGN KEY ([productId]) REFERENCES [dbo].[Product]([id]) ON DELETE NO ACTION ON UPDATE CASCADE;

COMMIT TRAN;

END TRY
BEGIN CATCH

IF @@TRANCOUNT > 0
BEGIN
    ROLLBACK TRAN;
END;
THROW

END CATCH
